permalink: /:year/:title

collections:
  archives:
    output: true
    
_options:
  content:
    format: p h1 h2 h3 h4 h5 h6 pre address div
    bold: true
    italic: true
    numberedlist: true
    code: true
    table: true
    right: align-to-right
    center: align-to-center
    embed: true
    link: true
    undo: true
    redo: true
    underline: true
    strike: true
    subscript: true
    superscript: true
    image: true
    bulletedlist: true
    styles: /assets/editor.css


page_blocks: []
_array_structures:
  page_blocks:
    - label: Banner A
      icon: ballot
      value:
        _id: banner-a
        background_image:
        heading:
        sub-heading:
    - label: Banner B
      icon: format_quote
      value:
        _id: banner-b
        background_image:
        line-1:
        line-2:
        line-3:
        link-text:
        link_url:
    - label: Split Banner
      icon: ballot
      value:
        _id: banner-split
        background_image:
        content_html:
    - label: Text Block
      icon: ballot
      value:
        _id: text-block
        content_html:
    - label: Image and text grid
      icon: ballot
      value:
        _id: image-text-grid
        first-pic-right: false
        layer:
          - picture_image:
            heading:
            text:
